# Generated by Django 4.2.2 on 2023-06-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.PositiveIntegerField()),
                ('person', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=10)),
                ('bed', models.CharField(max_length=1)),
            ],
        ),
    ]
